### ISSUE TITLE
CORS problem

### ISSUE THREAD

**Issue by koinov** [tonlabs/ton-dev-cli#1]
It seems CORS problem appears when /graphql/ request is made. 

I'm running ReactApp with TON-CLIENT-WEB-JS library to perform call to Node SE running on http://0.0.0.0 ReactApp is running on http://0.0.0.0:3000. 

Requests like: ton.queries.blocks.query(...) work well, but 
ton.contracts.deploy(...) reports CORS problem.

**Comment by melsomino** [comment]
I think your question related to web-js client not to CLI tool.
https://github.com/tonlabs/ton-client-web-js
I have reposted you issue https://github.com/tonlabs/ton-client-web-js/issues/2
